/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cuenta;

import Conexion.ConexionBD;
import Movimiento.ModalMovimiento;
import Rubros.ModalRubros;
import static Trabajo.ModalTrabajo.DCFechaIngreso;
import static Trabajo.ModalTrabajo.DCFechaSalida;
import alertas.principal.ErrorAlert;
import alertas.principal.SuccessAlert;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author criso
 */
public class ModalCuenta extends javax.swing.JFrame {

    static ConexionBD cc = new ConexionBD();
    static Connection cn = cc.conexion();
    static PreparedStatement ps;
    private Integer codigoSocio;

    public ModalCuenta(Integer codigoSocio) {
        initComponents();
        this.codigoSocio = codigoSocio;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        cerrar = new principal.MaterialButton();
        jPanel4 = new javax.swing.JPanel();
        MBRegistrar = new necesario.MaterialButton();
        MBLimpiar = new necesario.MaterialButton();
        jPanel5 = new javax.swing.JPanel();
        txtCuentaOficial = new app.bolivia.swing.JCTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEstado = new app.bolivia.swing.JCTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSaldoEfectivo = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSaldoCheque24 = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        DCFechaApertura = new rojeru_san.rsdate.RSDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txtSaldoCheque48 = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSaldoCheque = new app.bolivia.swing.JCTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSaldoLibreta = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();
        DCFechaUltimoMovimiento = new rojeru_san.rsdate.RSDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BtnRubros = new necesario.RSMaterialButtonCircle();
        BtnMovimientos = new necesario.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(58, 159, 171));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.gray));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("CUENTA");

        cerrar.setBackground(new java.awt.Color(251, 255, 255));
        cerrar.setForeground(new java.awt.Color(58, 159, 171));
        cerrar.setText("X");
        cerrar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Cerrar</h4> </body> </html>");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 511, Short.MAX_VALUE)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(58, 159, 171));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.gray));

        MBRegistrar.setBackground(new java.awt.Color(251, 255, 255));
        MBRegistrar.setForeground(new java.awt.Color(58, 159, 171));
        MBRegistrar.setText("REGISTRAR");
        MBRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MBRegistrar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        MBRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBRegistrarActionPerformed(evt);
            }
        });
        MBRegistrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MBRegistrarKeyTyped(evt);
            }
        });

        MBLimpiar.setBackground(new java.awt.Color(251, 255, 255));
        MBLimpiar.setForeground(new java.awt.Color(58, 159, 171));
        MBLimpiar.setText("lIMPIAR CAMPOS");
        MBLimpiar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        MBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(MBRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MBLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MBLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MBRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        jPanel5.setBorder(dropShadowBorder1);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCuentaOficial.setForeground(new java.awt.Color(58, 159, 171));
        txtCuentaOficial.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtCuentaOficial.setPlaceholder("Cuenta Oficial");
        jPanel5.add(txtCuentaOficial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 330, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Cuenta Oficial:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        txtEstado.setForeground(new java.awt.Color(58, 159, 171));
        txtEstado.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtEstado.setPlaceholder("Estado");
        jPanel5.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 330, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Estado:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        txtSaldoEfectivo.setForeground(new java.awt.Color(58, 159, 171));
        txtSaldoEfectivo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtSaldoEfectivo.setPlaceholder("Saldo Efectivo");
        jPanel5.add(txtSaldoEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 330, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Saldo Efectivo:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        txtSaldoCheque24.setForeground(new java.awt.Color(58, 159, 171));
        txtSaldoCheque24.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtSaldoCheque24.setPlaceholder("Saldo Cheque 24");
        jPanel5.add(txtSaldoCheque24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 330, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Saldo Cheque 24:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 20));

        DCFechaApertura.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        DCFechaApertura.setPlaceholder("Fecha Apertura");
        jPanel5.add(DCFechaApertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 330, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("AÑADIR INFORMACIÓN");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        txtSaldoCheque48.setForeground(new java.awt.Color(58, 159, 171));
        txtSaldoCheque48.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtSaldoCheque48.setPlaceholder("Saldo Cheque 48");
        jPanel5.add(txtSaldoCheque48, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 330, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Saldo Cheque 48:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 20));

        txtSaldoCheque.setForeground(new java.awt.Color(58, 159, 171));
        txtSaldoCheque.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtSaldoCheque.setPlaceholder("Saldo Cheque");
        jPanel5.add(txtSaldoCheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 330, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Saldo Cheque:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, 20));

        txtSaldoLibreta.setForeground(new java.awt.Color(58, 159, 171));
        txtSaldoLibreta.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtSaldoLibreta.setPlaceholder("Saldo Libreta");
        jPanel5.add(txtSaldoLibreta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 330, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Saldo Libreta:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, 20));

        DCFechaUltimoMovimiento.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        DCFechaUltimoMovimiento.setPlaceholder("Fecha Último Movimiento");
        jPanel5.add(DCFechaUltimoMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 330, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Movimiento:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Fecha Último ");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Fecha Apertura: ");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        BtnRubros.setText("RUBROS");
        BtnRubros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRubrosActionPerformed(evt);
            }
        });
        jPanel5.add(BtnRubros, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 200, 60));

        BtnMovimientos.setText("MOVIMIENTOS");
        BtnMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMovimientosActionPerformed(evt);
            }
        });
        jPanel5.add(BtnMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 200, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void MBRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBRegistrarActionPerformed
        String _txtCuentaOficial = txtCuentaOficial.getText();
        String _txtEstado = txtEstado.getText();
        String _txtSaldoEfectivo = txtSaldoEfectivo.getText();
        String _txtSaldoCheque24 = txtSaldoCheque24.getText();
        String _txtSaldoCheque48 = txtSaldoCheque48.getText();
        String _txtSaldoCheque = txtSaldoCheque.getText();
        String _txtSaldoLibreta = txtSaldoLibreta.getText();

        // Validaciones
        if (_txtCuentaOficial.isEmpty() || _txtEstado.isEmpty() || _txtSaldoEfectivo.isEmpty()
                || _txtSaldoCheque24.isEmpty() || _txtSaldoCheque48.isEmpty() || _txtSaldoCheque.isEmpty()
                || _txtSaldoLibreta.isEmpty() || DCFechaApertura.getDatoFecha() == null
                || DCFechaUltimoMovimiento.getDatoFecha() == null ){
            // Mostrar una alerta de error si algún campo está vacío
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("Error al ingresar los datos...");
            er.msj.setText("Por favor");
            er.msj1.setText("Complete todos los campos.");
            er.setVisible(true);
        } else {
            try {

                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date _DCFechaApertura = DCFechaApertura.getDatoFecha();
                String fechaApertura = dateFormat.format(_DCFechaApertura);

                Date _DCFechaUltimoMovimiento = DCFechaUltimoMovimiento.getDatoFecha();
                String fechaUltimoMovimiento = dateFormat.format(_DCFechaUltimoMovimiento);
                
                
                Integer cuentaOficial = Integer.valueOf(_txtCuentaOficial);
                Integer estado = Integer.valueOf(_txtEstado);
                
                
                Float saldoEfectivo = Float.valueOf(_txtSaldoEfectivo);
                Float saldoCheque24 = Float.valueOf(_txtSaldoCheque24);
                Float saldoCheque48 = Float.valueOf(_txtSaldoCheque48);
                Float saldoCheque = Float.valueOf(_txtSaldoCheque);
                Float saldoLibreta = Float.valueOf(_txtSaldoLibreta);

                String query = "INSERT INTO `cuenta` (codigoSocio, codigoMod, codigoProd, codigoM, codigoS, codigoO, fechaApertura, oficialCuenta, estado, saldoEfectivo, saldoCheque24, saldoCheque48, saldoCheque, saldoLibreta, fechaUltimoMov) "
                                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                ps = cn.prepareStatement(query);

       
                ps.setInt(1, codigoSocio);
                ps.setInt(2, 0);
                ps.setInt(3, 0);
                ps.setInt(4, 0);
                ps.setInt(5, 0);
                ps.setInt(6, 0);
                ps.setString(7, fechaApertura);
                ps.setInt(8, cuentaOficial);
                ps.setInt(9, estado );
                ps.setFloat(10, saldoEfectivo);
                ps.setFloat(11, saldoCheque24);
                ps.setFloat(12, saldoCheque48);
                ps.setFloat(13, saldoCheque);
                ps.setFloat(14, saldoLibreta);
                ps.setString(15, fechaUltimoMovimiento);
                
                ps.executeUpdate();

                limpiarCampos();

                SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                sa.titulo.setText("¡HECHO!");
                sa.msj.setText("SE HA REGISTRADO");
                sa.msj1.setText("LOS DATOS DEL TRABAJO!");
                sa.setVisible(true);

            } catch (SQLException e) {
                e.printStackTrace();
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("Error al ingresar los datos...");
                er.msj.setText("ERROR AL INGRESAR LOS DATOS");
                er.msj1.setText(e.getMessage());
                er.setVisible(true);
            } catch (NumberFormatException e) {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("Error al ingresar los datos...");
                er.msj.setText("Por favor, verificar:");
                er.msj1.setText("Valores numéricos válidos en los campos correspondientes.");
                er.setVisible(true);
            }

        }


    }//GEN-LAST:event_MBRegistrarActionPerformed

    private void MBRegistrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MBRegistrarKeyTyped

    }//GEN-LAST:event_MBRegistrarKeyTyped

    private void MBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBLimpiarActionPerformed

    }//GEN-LAST:event_MBLimpiarActionPerformed

    private void BtnRubrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRubrosActionPerformed
        ModalRubros mn = new ModalRubros();
        mn.setLocationRelativeTo(null);
        mn.setVisible(true);
    }//GEN-LAST:event_BtnRubrosActionPerformed

    private void BtnMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMovimientosActionPerformed
        ModalMovimiento mn = new ModalMovimiento(1,1);
        mn.setLocationRelativeTo(null);
        mn.setVisible(true);
    }//GEN-LAST:event_BtnMovimientosActionPerformed

    
    private void limpiarCampos() {
        txtCuentaOficial.setText("");
        txtEstado.setText("");
        txtSaldoEfectivo.setText("");
        txtSaldoCheque24.setText("");
        txtSaldoCheque48.setText("");
        txtSaldoCheque.setText("");
        txtSaldoLibreta.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModalCuenta(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private necesario.RSMaterialButtonCircle BtnMovimientos;
    private necesario.RSMaterialButtonCircle BtnRubros;
    public static rojeru_san.rsdate.RSDateChooser DCFechaApertura;
    public static rojeru_san.rsdate.RSDateChooser DCFechaUltimoMovimiento;
    private necesario.MaterialButton MBLimpiar;
    public static necesario.MaterialButton MBRegistrar;
    private principal.MaterialButton cerrar;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JLabel titulo;
    public static app.bolivia.swing.JCTextField txtCuentaOficial;
    public static app.bolivia.swing.JCTextField txtEstado;
    public static app.bolivia.swing.JCTextField txtSaldoCheque;
    public static app.bolivia.swing.JCTextField txtSaldoCheque24;
    public static app.bolivia.swing.JCTextField txtSaldoCheque48;
    public static app.bolivia.swing.JCTextField txtSaldoEfectivo;
    public static app.bolivia.swing.JCTextField txtSaldoLibreta;
    // End of variables declaration//GEN-END:variables
}
